# Generated by Django 2.2.19 on 2022-05-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('ph_num', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('message', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
