# Generated by Django 2.2.19 on 2022-05-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight', models.TextField()),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='docs_img')),
                ('desc', models.TextField()),
            ],
        ),
    ]
