# Generated by Django 2.2.19 on 2022-05-21 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='pic_fclty')),
                ('desc', models.TextField()),
                ('fb', models.CharField(max_length=50)),
                ('ig', models.CharField(max_length=50)),
                ('git', models.CharField(max_length=50)),
                ('lnkd', models.CharField(max_length=50)),
                ('twt', models.CharField(max_length=50)),
            ],
        ),
    ]
