# Generated by Django 2.2.19 on 2022-05-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculties',
            name='about',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
